# Welcome to Jekyll!
#

# Site settings
title: BioHackathon
description: 2019 November 12th - 16th, Campus des berges de Seine
owner: Elixir HUB # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: arcila@ebi.ac.uk
baseurl: "/biohackathon-europe" # the subpath of your site, e.g. /blog
url: "https://elixir-europe.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/biohackathon
  github: https://github.com/elixir-europe/BioHackathon
  #linkedin-square: https://www.linkedin.com/company/9501702
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:bh2018paris@elixir-europe.org
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

collections:
  programmes:
    output: true
    permalink: /:collection/:path/
  landings:
    output: true
    permalink: /:collection/:path/
  committee:
    output: true
    permalink: /:collection/:path/        